### PR TITLE
fix: should return empty manifest list when no referrers are found

### LINKED ISSUE #51: bug: referrers API should return an empty list when it now returns null
According to the distribution [spec](https://github.com/opencontainers/distribution-spec/blob/main/spec.md#listing-referrers:~:text=If%20a%20query,the%20referrers%20list.), when referrers API is called with a digest that has no referrers or does not exist in the repository, an empty list must/may be returned. A correct example (from pr #34 ): 
image

The current main branch gives the following incorrect output:
image

### PR DESCRIPTION
**Pull request by wangxiaoxuan273**
Resolves #51 
Signed-off-by: wangxiaoxuan273 <wangxiaoxuan119@gmail.com>

Current output:
First test case: 0 referrers are found.
Second test case: call with a manifest digest that is nonexistent in the repository, returns an empty manifest list.
image

### CODE REVIEW

File: registry/handlers/referrers.go [hunk 1]
```diff
@@ -67,6 +67,9 @@ func (h *referrersHandler) GetReferrers(w http.ResponseWriter, r *http.Request)
 		}
 	}
 	referrers, err := h.generateReferrersList(h, h.Digest, artifactTypeFilter)
+	if len(referrers) == 0 {
+		referrers = []v1.Descriptor{}
+	}
```
Comment (shizhMSFT) [inline registry/handlers/referrers.go:72]: Always check error before processing any return values.

File: registry/handlers/referrers.go [hunk 2]
```diff
@@ -67,6 +67,9 @@ func (h *referrersHandler) GetReferrers(w http.ResponseWriter, r *http.Request)
 		}
 	}
 	referrers, err := h.generateReferrersList(h, h.Digest, artifactTypeFilter)
+	if len(referrers) == 0 {
```
Comment (shizhMSFT) [inline registry/handlers/referrers.go:70]: nit: 
```suggestion
	if referrers == nil {
```

File: registry/handlers/referrers.go (hunk 1 above)
Comment (wangxiaoxuan273) [reply registry/handlers/referrers.go:72]: Good point. Changed.

File: registry/handlers/referrers.go (hunk 2 above)
Comment (wangxiaoxuan273) [reply registry/handlers/referrers.go:70]: changed.

**Review by shizhMSFT — APPROVED** [review]
LGTM
